name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for Trusted Publishing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Configure poetry
      run: |
        poetry config virtualenvs.create false
    - name: Build package
      run: |
        poetry install
        poetry build
        echo "Built files in dist/:"
        ls -l dist/
        echo "Wheel file contents:"
        unzip -l dist/*.whl
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.11
      with:
        verbose: true
        verify_metadata: true
    # No need for username/password with Trusted Publishers 