name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for Trusted Publishing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/stella-workflow
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python - -y
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false
        poetry config repositories.pypi https://upload.pypi.org/legacy/
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Build package
      run: |
        poetry build
        echo "Built files in dist/:"
        ls -l dist/
        echo "Wheel file contents:"
        unzip -l dist/*.whl
        echo "Metadata contents:"
        unzip -p dist/*.whl "*.dist-info/METADATA" || true
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        verify-metadata: true
    # No need for username/password with Trusted Publishers 