name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for Trusted Publishing

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Be explicit about Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build package
      run: |
        poetry build
        ls -l dist/  # List contents of dist directory for debugging
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.11
    # No need for username/password with Trusted Publishers 